spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/clue?useTimezone=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      use-unfair-lock: true
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 200000 # 放容器先试试  240s，
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 100
      filters: stat,wall,log4j2
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true #合并多个DruidDataSource的监控数据

base:
  host: 127.0.0.1
  port: 8080
  jzurl: http://127.0.0.1:8080/old/showReport2.html?
  jzsolveurl: http://127.0.0.1:8080/old/showReport3.html?
  staturl: http://127.0.0.1:8080/old/showReport4.html?
  staturl2: http://127.0.0.1:8080/old/showReport5.html?


mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml